apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-http-service
  labels:
    app: my-http-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-http-service
  template:
    metadata:
      labels:
        app: my-http-service
    spec:
      containers:
      - name: my-http-service
        image: jebin90/my-http-service
        ports:
        - containerPort: 8080
        terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: my-http-service
spec:
  type: NodePort
  selector:
    app: my-http-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
